steps:
- name: gcr.io/cloud-builders/gcloud
  dir: app
  args:
  - kms
  - decrypt
  - --ciphertext-file=hikma-health-363641fc9dd2.json.enc
  - --plaintext-file=hikma-health-363641fc9dd2.json
  - --location=global
  - --keyring=hikma-nv-keyring
  - --key=hikma-nv-key
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hikma-health-backend-nv:$COMMIT_SHA',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'credential_file_arg=hikma-health-363641fc9dd2.json',
          '--build-arg', 'db_instance_arg=${_DB_INSTANCE}',
          '--build-arg', 'commit_sha_arg=$COMMIT_SHA',
          '--build-arg', 'db_password_arg=${_DB_PASSWORD}',
          '--build-arg', 'db_name_arg=${_DB_NAME}',
          '--build-arg', 'default_provider_id_arg=${_DEFAULT_PROVIDER_ID}',
          '--build-arg', 'photos_storage_bucket_arg=${_PHOTOS_STORAGE_BUCKET}',
          '--build-arg', 'exports_storage_bucket_arg=${_EXPORTS_STORAGE_BUCKET}',
          '.' ]
  dir: app
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a', 'CLOUDSDK_CONTAINER_CLUSTER=nv-cluster']
  args: ['set', 'image', 'deployment/hikma-health-backend-nv',
          'hikma-health-backend=gcr.io/$PROJECT_ID/hikma-health-backend-nv:$COMMIT_SHA']  
images:
- 'gcr.io/$PROJECT_ID/hikma-health-backend-nv:$COMMIT_SHA'
substitutions:
  _DB_INSTANCE: 'hikma-health:southamerica-east1:hikma-db-nv'
  _DB_NAME: 'nv_prod'
options:
  machineType: 'N1_HIGHCPU_8'
