apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: run-full-export
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: run-full-export
            image: gcr.io/hikma-health/hikma-health-backend-nv:c7b5a4faf05efa89e520cd70f37f746043d60119
            command:
            - /bin/bash
            - run-export.sh
          restartPolicy: OnFailure
